/**
 * ORCA — Simulated marine data layer.
 *
 * ⚠ All values here are DEMO/SIMULATED. They are deliberately plausible
 * for the Indian coastline (monsoon-season values, IMD/INCOIS-style
 * terminology) but MUST NOT be presented as live observations.
 *
 * Four regions are modelled with distinct risk signatures so that
 * switching region visibly changes the whole workspace:
 *   - Mumbai  : cyclone influence + high waves   (HIGH risk scenario)
 *   - Goa     : lightning cell + moderate swell  (MODERATE)
 *   - Kerala  : benign sea, rich PFZ upwelling   (LOW)
 *   - Chennai : rough sea NE + squally winds     (HIGH-moderate)
 */

import type { MarineRegion, RegionId } from "@/types/marine";
import { destinationPoint, irregularBlob, circlePolygon, bearingLabel } from "./map-utils";

export const REGIONS: Record<RegionId, MarineRegion> = {
  /* ══════════════════════════ MUMBAI ══════════════════════════ */
  mumbai: {
    id: "mumbai",
    name: "Mumbai Coast",
    nameHi: "मुंबई तट",
    center: { lat: 18.92, lng: 72.62 },
    defaultZoom: 9,
    coastline: [
      { lat: 20.15, lng: 72.85 },
      { lat: 19.72, lng: 72.92 },
      { lat: 19.42, lng: 72.83 },
      { lat: 19.2, lng: 72.85 },
      { lat: 19.0, lng: 72.84 },
      { lat: 18.85, lng: 72.88 },
      { lat: 18.68, lng: 72.87 },
      { lat: 18.5, lng: 72.81 },
      { lat: 18.32, lng: 72.86 },
    ],
    vessel: {
      id: "vessel-mumbai",
      name: "Matsyashree-7",
      type: "fishing",
      position: { lat: 18.95, lng: 72.72 },
      headingDeg: 225,
      speedKnots: 0,
      status: "anchored",
    },
    hazardZones: [
      {
        id: "hz-mum-waves",
        label: "High wave zone",
        labelHi: "उच्च तरंग क्षेत्र",
        type: "highWaves",
        center: { lat: 18.82, lng: 72.55 },
        radiusKm: 26,
        polygon: irregularBlob({ lat: 18.82, lng: 72.55 }, 26, 7, 0.3),
        severity: "high",
        detail: "Wave heights 3.0–3.6 m with 9 s period; small vessels advised to stay in harbour.",
        detailHi: "तरंग ऊंचाई 3.0–3.6 मी, छोटे जहाजों को बंदरगाह में रहने की सलाह।",
      },
      {
        id: "hz-mum-squall",
        label: "Squally wind cell",
        labelHi: "आंधी-वातावरण क्षेत्र",
        type: "roughSea",
        center: { lat: 19.28, lng: 72.42 },
        radiusKm: 18,
        polygon: irregularBlob({ lat: 19.28, lng: 72.42 }, 18, 13, 0.34),
        severity: "moderate",
        detail: "Squally wind 40–50 km/h gusts in isolated cells; reduced visibility.",
        detailHi: "40–50 किमी/घंटा झोंके, दृश्यता कम।",
      },
    ],
    safeZones: [
      {
        id: "sz-mum-versova",
        label: "Versova near-shore anchorage",
        labelHi: "वर्सोवा तटीय लंगर क्षेत्र",
        center: { lat: 19.13, lng: 72.8 },
        radiusKm: 9,
        reason: "Sheltered near-shore water; wave height < 1.2 m and leeward of cyclone track.",
        reasonHi: "सुरक्षित तटीय जल; तरंग < 1.2 मी, चक्रवात मार्ग की चौड़ाई में।",
      },
    ],
    pfzZones: [
      {
        id: "pfz-mum-1",
        label: "PFZ-01 · Offshore Versova",
        labelHi: "PFZ-01 · वर्सोवा दूरस्थ",
        polygon: irregularBlob({ lat: 18.6, lng: 72.46 }, 8.5, 21, 0.22, 14),
        center: { lat: 18.6, lng: 72.46 },
        distanceKm: 41.6,
        sst: 28.4,
        chlorophyll: 2.8,
        signals: { sstFront: true, chlorophyllElevated: true, thermoclineShallow: true },
        expectedSpecies: ["Indian mackerel", "Oil sardine"],
        depthM: 42,
      },
      {
        id: "pfz-mum-2",
        label: "PFZ-02 · Northwest grounds",
        labelHi: "PFZ-02 · उत्तर-पश्चिम क्षेत्र",
        polygon: irregularBlob({ lat: 19.42, lng: 72.5 }, 7.5, 33, 0.24, 14),
        center: { lat: 19.42, lng: 72.5 },
        distanceKm: 56.3,
        sst: 28.9,
        chlorophyll: 1.9,
        signals: { sstFront: true, chlorophyllElevated: false, thermoclineShallow: false },
        expectedSpecies: ["Ribbonfish", "Cuttlefish"],
        depthM: 55,
      },
    ],
    cyclone: (() => {
      const center = destinationPoint({ lat: 18.95, lng: 72.72 }, 318, 80);
      return {
        name: "Asna",
        category: "Cyclonic Storm" as const,
        center,
        distanceKm: 80,
        bearing: bearingLabel({ lat: 18.95, lng: 72.72 }, center),
        windKmph: 75,
        movement: "NNW 12 km/h",
      };
    })(),
    conditions: {
      waveHeightM: 3.2,
      wavePeriodS: 9,
      windSpeedKmph: 28,
      windGustKmph: 42,
      windDirection: "SW",
      sst: 28.6,
      chlorophyll: 1.4,
      currentKnots: 1.8,
      visibilityKm: 4,
      advisory: "Squally weather with wind speed 40–50 km/h likely along Maharashtra coast; fishermen advised not to venture into sea.",
      advisoryHi: "महाराष्ट्र तट पर 40–50 किमी/घंटा तेज़ हवाएं संभव; मछुआरों को समुद्र में न जाने की सलाह।",
      advisoryActive: true,
      tide: { high: "04:35", low: "10:52" },
      sunrise: "06:24",
      sunset: "18:47",
      updatedAt: "07:40 IST",
    },
    suggestedRoute: {
      id: "route-mum-1",
      label: "Suggested safer path",
      labelHi: "सुझाया गया सुरक्षित मार्ग",
      path: [
        { lat: 18.95, lng: 72.72 },
        { lat: 19.02, lng: 72.76 },
        { lat: 19.08, lng: 72.79 },
        { lat: 19.13, lng: 72.8 },
      ],
      distanceKm: 22.4,
      etaMinutes: 85,
      avoids: ["High wave zone", "Cyclone influence area"],
    },
    boundary: {
      label: "Territorial waters limit (12 NM) · simulated",
      path: [
        { lat: 20.0, lng: 72.52 },
        { lat: 19.4, lng: 72.38 },
        { lat: 18.8, lng: 72.3 },
        { lat: 18.2, lng: 72.34 },
      ],
    },
  },

  /* ══════════════════════════ GOA ══════════════════════════ */
  goa: {
    id: "goa",
    name: "Goa Coast",
    nameHi: "गोवा तट",
    center: { lat: 15.42, lng: 73.78 },
    defaultZoom: 10,
    coastline: [
      { lat: 15.95, lng: 73.9 },
      { lat: 15.78, lng: 73.83 },
      { lat: 15.62, lng: 73.76 },
      { lat: 15.5, lng: 73.79 },
      { lat: 15.4, lng: 73.77 },
      { lat: 15.28, lng: 73.79 },
      { lat: 15.12, lng: 73.87 },
      { lat: 14.98, lng: 73.94 },
    ],
    vessel: {
      id: "vessel-goa",
      name: "Sagarganga-2",
      type: "fishing",
      position: { lat: 15.38, lng: 73.72 },
      headingDeg: 40,
      speedKnots: 0,
      status: "anchored",
    },
    hazardZones: [
      {
        id: "hz-goa-lightning",
        label: "Thunderstorm / lightning cell",
        labelHi: "आंधी / बिजली गिरने का क्षेत्र",
        type: "lightning",
        center: { lat: 15.58, lng: 73.82 },
        radiusKm: 14,
        polygon: irregularBlob({ lat: 15.58, lng: 73.82 }, 14, 5, 0.3),
        severity: "moderate",
        detail: "Isolated thunderstorms with lightning likely; avoid open water during cells.",
        detailHi: "अलग-अलग तूफ़ान और बिजली संभव; खुले पानी में जाने से बचें।",
      },
      {
        id: "hz-goa-swell",
        label: "Moderate swell zone",
        labelHi: "मध्यम लहर क्षेत्र",
        type: "highWaves",
        center: { lat: 15.14, lng: 73.9 },
        radiusKm: 18,
        polygon: irregularBlob({ lat: 15.14, lng: 73.9 }, 18, 9, 0.26),
        severity: "moderate",
        detail: "Swell 2.0–2.4 m near shore; operate with caution near river mouths.",
        detailHi: "तट के पास लहर 2.0–2.4 मी; नदी मुहाने के पास सावधानी रखें।",
      },
    ],
    safeZones: [
      {
        id: "sz-goa-mormugao",
        label: "Mormugao harbour lee",
        labelHi: "मरमुगाओ बंदरगाह छाया क्षेत्र",
        center: { lat: 15.44, lng: 73.79 },
        radiusKm: 7,
        reason: "Breakwater shelter; wave height < 1.0 m within harbour approach.",
        reasonHi: "वेव-ब्रेकर आश्रय; बंदरगाह दृष्टिकोण में लहर < 1.0 मी।",
      },
    ],
    pfzZones: [
      {
        id: "pfz-goa-1",
        label: "PFZ-03 · Offshore Candolim",
        labelHi: "PFZ-03 · कैंडोलिम दूरस्थ",
        polygon: irregularBlob({ lat: 15.56, lng: 73.96 }, 7.5, 17, 0.2, 14),
        center: { lat: 15.56, lng: 73.96 },
        distanceKm: 24.8,
        sst: 29.1,
        chlorophyll: 3.4,
        signals: { sstFront: true, chlorophyllElevated: true, thermoclineShallow: false },
        expectedSpecies: ["Indian mackerel", "Anchovies"],
        depthM: 35,
      },
      {
        id: "pfz-goa-2",
        label: "PFZ-04 · South grounds",
        labelHi: "PFZ-04 · दक्षिण क्षेत्र",
        polygon: irregularBlob({ lat: 15.12, lng: 73.86 }, 6.5, 29, 0.22, 14),
        center: { lat: 15.12, lng: 73.86 },
        distanceKm: 31.9,
        sst: 29.0,
        chlorophyll: 2.6,
        signals: { sstFront: false, chlorophyllElevated: true, thermoclineShallow: true },
        expectedSpecies: ["Oil sardine", "Tuna"],
        depthM: 48,
      },
    ],
    cyclone: null,
    conditions: {
      waveHeightM: 2.1,
      wavePeriodS: 8,
      windSpeedKmph: 18,
      windGustKmph: 26,
      windDirection: "W",
      sst: 29.2,
      chlorophyll: 2.1,
      currentKnots: 1.1,
      visibilityKm: 7,
      advisory: "Thunderstorm with lightning likely at isolated places over Goa coast; moderate swell near shore.",
      advisoryHi: "गोवा तट पर अलग-अलग जगह तूफ़ान और बिजली संभव; तट के पास मध्यम लहरें।",
      advisoryActive: false,
      tide: { high: "05:12", low: "11:30" },
      sunrise: "06:18",
      sunset: "18:52",
      updatedAt: "07:40 IST",
    },
    suggestedRoute: {
      id: "route-goa-1",
      label: "Suggested safer path",
      labelHi: "सुझाया गया सुरक्षित मार्ग",
      path: [
        { lat: 15.38, lng: 73.72 },
        { lat: 15.41, lng: 73.76 },
        { lat: 15.44, lng: 73.79 },
      ],
      distanceKm: 8.7,
      etaMinutes: 35,
      avoids: ["Thunderstorm cell"],
    },
    boundary: {
      label: "Territorial waters limit (12 NM) · simulated",
      path: [
        { lat: 15.85, lng: 73.52 },
        { lat: 15.5, lng: 73.42 },
        { lat: 15.1, lng: 73.5 },
        { lat: 14.9, lng: 73.6 },
      ],
    },
  },

  /* ══════════════════════════ KERALA ══════════════════════════ */
  kerala: {
    id: "kerala",
    name: "Kerala Coast",
    nameHi: "केरल तट",
    center: { lat: 9.7, lng: 75.5 },
    defaultZoom: 9,
    coastline: [
      { lat: 10.3, lng: 75.32 },
      { lat: 10.05, lng: 75.42 },
      { lat: 9.85, lng: 75.5 },
      { lat: 9.65, lng: 75.6 },
      { lat: 9.45, lng: 75.7 },
      { lat: 9.25, lng: 75.82 },
      { lat: 9.05, lng: 75.92 },
      { lat: 8.85, lng: 76.0 },
    ],
    vessel: {
      id: "vessel-kerala",
      name: "Kadalamma-4",
      type: "fishing",
      position: { lat: 9.72, lng: 75.38 },
      headingDeg: 200,
      speedKnots: 0,
      status: "anchored",
    },
    hazardZones: [
      {
        id: "hz-ker-swell",
        label: "Long-period swell advisory",
        labelHi: "दीर्घ-अवधि लहर सलाह",
        type: "highWaves",
        center: { lat: 9.95, lng: 75.18 },
        radiusKm: 16,
        polygon: irregularBlob({ lat: 9.95, lng: 75.18 }, 16, 4, 0.24),
        severity: "moderate",
        detail: "Long-period swell 1.6–1.9 m; small craft should avoid outer grounds at dawn.",
        detailHi: "लंबी अवधि की लहरें 1.6–1.9 मी; भोर में बाहरी क्षेत्रों से बचें।",
      },
    ],
    safeZones: [
      {
        id: "sz-ker-kochi",
        label: "Kochi inlet approach",
        labelHi: "कोच्चि प्रवेश द्वार",
        center: { lat: 9.86, lng: 75.4 },
        radiusKm: 8,
        reason: "Calm near-inlet water; swell attenuates behind headland.",
        reasonHi: "प्रवेश द्वार के पास शांत जल; सुरक्षित क्षेत्र।",
      },
    ],
    pfzZones: [
      {
        id: "pfz-ker-1",
        label: "PFZ-05 · Upwelling front",
        labelHi: "PFZ-05 · अपवाह फ्रंट",
        polygon: irregularBlob({ lat: 9.5, lng: 75.14 }, 8.5, 11, 0.22, 14),
        center: { lat: 9.5, lng: 75.14 },
        distanceKm: 28.1,
        sst: 28.2,
        chlorophyll: 4.1,
        signals: { sstFront: true, chlorophyllElevated: true, thermoclineShallow: true },
        expectedSpecies: ["Ribbonfish", "Yellowfin tuna", "Squid"],
        depthM: 60,
      },
      {
        id: "pfz-ker-2",
        label: "PFZ-06 · South shelf edge",
        labelHi: "PFZ-06 · दक्षिण शेल्फ किनारा",
        polygon: irregularBlob({ lat: 9.2, lng: 75.3 }, 7, 19, 0.24, 14),
        center: { lat: 9.2, lng: 75.3 },
        distanceKm: 59.4,
        sst: 28.5,
        chlorophyll: 3.2,
        signals: { sstFront: true, chlorophyllElevated: true, thermoclineShallow: false },
        expectedSpecies: ["Indian mackerel", "Carangids"],
        depthM: 78,
      },
    ],
    cyclone: null,
    conditions: {
      waveHeightM: 1.4,
      wavePeriodS: 7,
      windSpeedKmph: 12,
      windGustKmph: 18,
      windDirection: "NW",
      sst: 28.4,
      chlorophyll: 3.8,
      currentKnots: 0.9,
      visibilityKm: 9,
      advisory: "Generally fair conditions; long-period swell noted offshore during early morning hours.",
      advisoryHi: "सामान्य रूप से अनुकूल परिस्थितियां; भोर में तट से दूर लंबी लहरें दर्ज।",
      advisoryActive: false,
      tide: { high: "03:58", low: "10:14" },
      sunrise: "06:10",
      sunset: "18:41",
      updatedAt: "07:40 IST",
    },
    suggestedRoute: {
      id: "route-ker-1",
      label: "Suggested safer path",
      labelHi: "सुझाया गया सुरक्षित मार्ग",
      path: [
        { lat: 9.72, lng: 75.38 },
        { lat: 9.78, lng: 75.39 },
        { lat: 9.84, lng: 75.4 },
        { lat: 9.86, lng: 75.4 },
      ],
      distanceKm: 15.6,
      etaMinutes: 55,
      avoids: ["Long-period swell"],
    },
    boundary: {
      label: "Territorial waters limit (12 NM) · simulated",
      path: [
        { lat: 10.2, lng: 74.98 },
        { lat: 9.8, lng: 75.05 },
        { lat: 9.4, lng: 75.3 },
        { lat: 9.0, lng: 75.55 },
      ],
    },
  },

  /* ══════════════════════════ CHENNAI ══════════════════════════ */
  chennai: {
    id: "chennai",
    name: "Chennai Coast",
    nameHi: "चेन्नई तट",
    center: { lat: 13.2, lng: 80.42 },
    defaultZoom: 9,
    coastline: [
      { lat: 13.78, lng: 80.24 },
      { lat: 13.55, lng: 80.27 },
      { lat: 13.34, lng: 80.29 },
      { lat: 13.14, lng: 80.31 },
      { lat: 12.94, lng: 80.33 },
      { lat: 12.74, lng: 80.37 },
      { lat: 12.54, lng: 80.41 },
      { lat: 12.34, lng: 80.46 },
    ],
    vessel: {
      id: "vessel-chennai",
      name: "Alaiyarasi-9",
      type: "fishing",
      position: { lat: 13.18, lng: 80.55 },
      headingDeg: 60,
      speedKnots: 0,
      status: "anchored",
    },
    hazardZones: [
      {
        id: "hz-chn-rough",
        label: "Rough sea zone",
        labelHi: "कठोर समुद्र क्षेत्र",
        type: "roughSea",
        center: { lat: 13.48, lng: 80.88 },
        radiusKm: 24,
        polygon: irregularBlob({ lat: 13.48, lng: 80.88 }, 24, 15, 0.28),
        severity: "high",
        detail: "Wind-waves 2.8–3.4 m offshore NE; crossings dangerous for small vessels.",
        detailHi: "उत्तर-पूर्व में 2.8–3.4 मी हवा-तरंगें; छोटे जहाजों के लिए खतरनाक।",
      },
      {
        id: "hz-chn-lightning",
        label: "Evening lightning risk",
        labelHi: "सायं बिजली जोखिम",
        type: "lightning",
        center: { lat: 12.98, lng: 80.66 },
        radiusKm: 15,
        polygon: irregularBlob({ lat: 12.98, lng: 80.66 }, 15, 23, 0.3),
        severity: "moderate",
        detail: "Convection building after 15:00 IST; lightning cells possible seaward.",
        detailHi: "15:00 IST के बाद बादल बनना; समुद्र की ओर बिजली संभव।",
      },
    ],
    safeZones: [
      {
        id: "sz-chn-kasimedu",
        label: "Kasimedu harbour approach",
        labelHi: "कासीमेदु बंदरगाह दृष्टिकोण",
        center: { lat: 13.12, lng: 80.42 },
        radiusKm: 7,
        reason: "Lee of Chennai port breakwater; wave height < 1.1 m.",
        reasonHi: "चेन्नई बंदरगाह की छाया में; लहर < 1.1 मी।",
      },
    ],
    pfzZones: [
      {
        id: "pfz-chn-1",
        label: "PFZ-07 · Offshore Mahabalipuram",
        labelHi: "PFZ-07 · महाबलीपुरम दूरस्थ",
        polygon: irregularBlob({ lat: 12.9, lng: 80.42 }, 8, 27, 0.22, 14),
        center: { lat: 12.9, lng: 80.42 },
        distanceKm: 33.2,
        sst: 29.3,
        chlorophyll: 2.2,
        signals: { sstFront: true, chlorophyllElevated: true, thermoclineShallow: false },
        expectedSpecies: ["Seer fish", "Grouper", "Silver pomfret"],
        depthM: 44,
      },
      {
        id: "pfz-chn-2",
        label: "PFZ-08 · Northern grounds",
        labelHi: "PFZ-08 · उत्तरी क्षेत्र",
        polygon: irregularBlob({ lat: 13.62, lng: 80.52 }, 6.5, 35, 0.26, 14),
        center: { lat: 13.62, lng: 80.52 },
        distanceKm: 49.8,
        sst: 29.5,
        chlorophyll: 1.8,
        signals: { sstFront: false, chlorophyllElevated: false, thermoclineShallow: true },
        expectedSpecies: ["Anchovies", "Carangids"],
        depthM: 38,
      },
    ],
    cyclone: null,
    conditions: {
      waveHeightM: 2.8,
      wavePeriodS: 9,
      windSpeedKmph: 24,
      windGustKmph: 36,
      windDirection: "NE",
      sst: 29.4,
      chlorophyll: 1.6,
      currentKnots: 1.4,
      visibilityKm: 5,
      advisory: "Wind-waves 2.8–3.4 m offshore; squally wind likely evening. Fisherfolk advised caution.",
      advisoryHi: "तट से दूर 2.8–3.4 मी हवा-तरंगें; शाम को तेज़ हवाएं संभव। सावधानी रखें।",
      advisoryActive: true,
      tide: { high: "05:47", low: "12:05" },
      sunrise: "05:52",
      sunset: "18:16",
      updatedAt: "07:40 IST",
    },
    suggestedRoute: {
      id: "route-chn-1",
      label: "Suggested safer path",
      labelHi: "सुझाया गया सुरक्षित मार्ग",
      path: [
        { lat: 13.18, lng: 80.55 },
        { lat: 13.16, lng: 80.49 },
        { lat: 13.13, lng: 80.44 },
        { lat: 13.12, lng: 80.42 },
      ],
      distanceKm: 14.9,
      etaMinutes: 60,
      avoids: ["Rough sea zone", "Evening lightning cells"],
    },
    boundary: {
      label: "Territorial waters limit (12 NM) · simulated",
      path: [
        { lat: 13.7, lng: 80.72 },
        { lat: 13.3, lng: 80.86 },
        { lat: 12.9, lng: 80.98 },
        { lat: 12.5, lng: 81.05 },
      ],
    },
  },
};

export const REGION_ORDER: RegionId[] = ["mumbai", "goa", "kerala", "chennai"];

export function getRegion(id: RegionId): MarineRegion {
  return REGIONS[id];
}

/** Cyclone influence radii (km) — wind field rings drawn on the map. */
export const CYCLONE_RINGS_KM = [30, 60, 95];

export { circlePolygon };
